CREATE TABLE Endereco (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    cep VARCHAR(10) NOT NULL
);

CREATE TABLE Produto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL,
    preco DOUBLE PRECISION NOT NULL
);

CREATE TABLE Cliente (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(15),
    email VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    endereco_id INT,
    FOREIGN KEY (endereco_id) REFERENCES Endereco(id)
);

CREATE TABLE Funcionario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(15),
    email VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    cargo VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    salario DOUBLE PRECISION NOT NULL, 
    endereco_id INT,
    FOREIGN KEY (endereco_id) REFERENCES Endereco(id)
);


CREATE TABLE EmpresaCliente (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    representante_id INT,
    cnpj VARCHAR(18) UNIQUE NOT NULL,
    telefone VARCHAR(15),
    razaoSocial VARCHAR(255) NOT NULL,
    nomeFantasia VARCHAR(255) NOT NULL,
    tamanho INT,
    FOREIGN KEY (representante_id) REFERENCES Cliente(id)
);

CREATE TABLE Plano (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeFantasia VARCHAR(255) NOT NULL,
    dataInicio DATE NOT NULL,
    dataFinal DATE NOT NULL,
    valor DOUBLE PRECISION NOT NULL,
    produto_id INT,
    FOREIGN KEY (produto_id) REFERENCES Produto(id)
);


CREATE TABLE Contrato (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id INT,
    empresa_cliente_id INT,
    plano_id INT,
    FOREIGN KEY (funcionario_id) REFERENCES Funcionario(id),
    FOREIGN KEY (empresa_cliente_id) REFERENCES EmpresaCliente(id),
    FOREIGN KEY (plano_id) REFERENCES Plano(id)
);
