CREATE TABLE
    Usuario (
        id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(255) NOT NULL,
        telefone VARCHAR(15),
        email VARCHAR(255) NOT NULL,
        cpf VARCHAR(14) UNIQUE NOT NULL,
        cargo VARCHAR(255) NOT NULL,
        senha VARCHAR(255) NOT NULL
    );

CREATE TABLE
    Cliente (
        id_cliente INT PRIMARY KEY,
        FOREIGN KEY (id_cliente) REFERENCES Usuario (id_usuario) ON DELETE CASCADE
    );

CREATE TABLE
    Funcionario (
        id_funcionario INT PRIMARY KEY,
        salario FLOAT NOT NULL,
        FOREIGN KEY (id_funcionario) REFERENCES Usuario (id_usuario) ON DELETE CASCADE
    );

CREATE TABLE
    Plano (
        id_plano INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nomeFantasia VARCHAR(255) NOT NULL,
        tipoPlano VARCHAR(255) NOT NULL,
        dataInicio DATE NOT NULL,
        dataFinal DATE NOT NULL,
        valor FLOAT NOT NULL
    );

CREATE TABLE
    Produto (
        id_produto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(255) NOT NULL,
        preco FLOAT NOT NULL,
        id_plano INT,
        FOREIGN KEY (id_plano) REFERENCES Plano (id_plano) ON DELETE CASCADE
    );

CREATE TABLE
    EmpresaCliente (
        id_empresaCliente INT GENERATED BY DEFAULT AS IDENTITY,
        cnpj VARCHAR(18) UNIQUE NOT NULL,
        telefone VARCHAR(15),
        razaoSocial VARCHAR(255) NOT NULL,
        nomeFantasia VARCHAR(255) NOT NULL,
        tamanho INT,
        id_cliente INT,
        PRIMARY KEY (id_empresaCliente),
        FOREIGN KEY (id_cliente) REFERENCES Cliente (id_cliente)
    );

CREATE TABLE
    Endereco (
        id_endereco INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        rua VARCHAR(255) NOT NULL,
        numero VARCHAR(10) NOT NULL,
        cidade VARCHAR(255) NOT NULL,
        estado VARCHAR(255) NOT NULL,
        cep VARCHAR(10) NOT NULL,
        id_usuario INT,
        FOREIGN KEY (id_usuario) REFERENCES Usuario (id_usuario) ON DELETE CASCADE
    );

CREATE TABLE
    Contrato (
        id_contrato INT GENERATED BY DEFAULT AS IDENTITY,
        funcionario_id INT,
        empresa_cliente_id INT,
        plano_id INT,
        PRIMARY key (
            id_contrato,
            empresa_cliente_id,
            plano_id,
            funcionario_id
        ) FOREIGN KEY (funcionario_id) REFERENCES Funcionario (id_funcionario),
        FOREIGN KEY (empresa_cliente_id) REFERENCES EmpresaCliente (id_empresaCliente),
        FOREIGN KEY (plano_id) REFERENCES Plano (id_plano)
    );